package com.example.there.findclips.di

object Dependencies {
    const val SPOTIFY_API_RETROFIT = "SPOTIFY_API_RETROFIT"
    const val SPOTIFY_ACCOUNTS_API_RETROFIT = "SPOTIFY_ACCOUNTS_API_RETROFIT"
    const val SPOTIFY_CHARTS_RETROFIT = "SPOTIFY_CHARTS_RETROFIT"

    const val YOUTUBE_API_RETROFIT = "YOUTUBE_API_RETROFIT"
}