package com.example.there.domain.usecases

object UseCaseParams {
    const val PARAM_CLIENT_ID = "PARAM_CLIENT_ID"
    const val PARAM_CLIENT_SECRET = "PARAM_CLIENT_SECRET"

    const val PARAM_ACCESS_TOKEN = "PARAM_ACCESS_TOKEN"

    const val PARAM_TRACK_ID = "PARAM_TRACK_ID"

    const val PARAM_VIDEO_QUERY = "PARAM_VIDEO_QUERY"
    const val PARAM_PAGE_TOKEN = "PARAM_PAGE_TOKEN"

    const val PARAM_LOAD_MORE = "PARAM_MORE"

    const val PARAM_VIDEO_ID = "PARAM_VIDEO_ID"

    const val PARAM_VIDEOS = "PARAM_VIDEOS"

    const val PARAM_SEARCH_ALL_QUERY = "PARAM_SEARCH_ALL_QUERY"

    const val PARAM_CATEGORY_ID = "PARAM_CATEGORY_ID"

    const val PARAM_PLAYLIST_ID = "PARAM_PLAYLIST_ID"
    const val PARAM_USER_ID = "PARAM_USER_ID"

    const val PARAM_ALBUM_ID = "PARAM_ALBUM_ID"
    const val PARAM_ARTIST_IDS = "PARAM_ARTIST_IDS"

    const val PARAM_ARTIST_ID = "PARAM_ARTIST_ID"

    const val PARAM_ALBUM = "PARAM_ALBUM"
    const val PARAM_ARTIST = "PARAM_ARTIST"
    const val PARAM_CATEGORY = "PARAM_CATEGORY"
    const val PARAM_SPOTIFY_PLAYLIST = "PARAM_SPOTIFY_PLAYLIST"
    const val PARAM_TRACK = "PARAM_TRACK"

    const val PARAM_OFFSET = "PARAM_OFFSET"

    const val PARAM_VIDEO_PLAYLIST = "PARAM_VIDEO_PLAYLIST"
    const val PARAM_VIDEO = "PARAM_VIDEO"
}