/**
 * Spotify Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.clipfinder.spotify.api.models


import com.squareup.moshi.Json

/**
 *
 * @param height The image height in pixels. If unknown: null or not returned.
 * @param url The source URL of the image.
 * @param width The image width in pixels. If unknown: null or not returned.
 */

data class ImageObject(
    /* The image height in pixels. If unknown: null or not returned. */
    @Json(name = "height")
    val height: Int? = null,
    /* The source URL of the image. */
    @Json(name = "url")
    val url: String? = null,
    /* The image width in pixels. If unknown: null or not returned. */
    @Json(name = "width")
    val width: Int? = null
)

