/**
 * Spotify Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.clipfinder.spotify.api.models


import com.squareup.moshi.Json

/**
 *
 * @param name The new name for the playlist, for example \"My New Playlist Title\"
 * @param public If true the playlist will be public, if false it will be private.
 * @param collaborative If true , the playlist will become collaborative and other users will be able to modify the playlist in their Spotify client. Note: You can only set collaborative to true on non-public playlists.
 * @param description Value for playlist description as displayed in Spotify Clients and in the Web API.
 */

data class PlaylistDetailsBody(
    /* The new name for the playlist, for example \"My New Playlist Title\" */
    @Json(name = "name")
    val name: String? = null,
    /* If true the playlist will be public, if false it will be private. */
    @Json(name = "public")
    val public: Boolean? = null,
    /* If true , the playlist will become collaborative and other users will be able to modify the playlist in their Spotify client. Note: You can only set collaborative to true on non-public playlists. */
    @Json(name = "collaborative")
    val collaborative: Boolean? = null,
    /* Value for playlist description as displayed in Spotify Clients and in the Web API. */
    @Json(name = "description")
    val description: String? = null
)

