/**
 * Spotify Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.clipfinder.spotify.api.models


import com.squareup.moshi.Json

/**
 *
 * @param start
 * @param duration
 * @param confidence
 * @param loudnessStart
 * @param loudnessMax
 * @param loudnessMaxTime
 * @param loudnessEnd
 * @param pitches
 * @param timbre
 */

data class SegmentObject(
    @Json(name = "start")
    val start: java.math.BigDecimal? = null,
    @Json(name = "duration")
    val duration: java.math.BigDecimal? = null,
    @Json(name = "confidence")
    val confidence: java.math.BigDecimal? = null,
    @Json(name = "loudness_start")
    val loudnessStart: java.math.BigDecimal? = null,
    @Json(name = "loudness_max")
    val loudnessMax: java.math.BigDecimal? = null,
    @Json(name = "loudness_max_time")
    val loudnessMaxTime: java.math.BigDecimal? = null,
    @Json(name = "loudness_end")
    val loudnessEnd: java.math.BigDecimal? = null,
    @Json(name = "pitches")
    val pitches: List<java.math.BigDecimal>? = null,
    @Json(name = "timbre")
    val timbre: List<java.math.BigDecimal>? = null
)

