/**
 * Spotify Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.clipfinder.spotify.api.models

import com.squareup.moshi.Json

/**
 *
 * @param collaborative
 * @param description
 * @param externalUrls
 * @param href
 * @param id
 * @param images
 * @param name
 * @param owner
 * @param public
 * @param snapshotId
 * @param tracks
 * @param type
 * @param uri
 */

data class SimplifiedPlaylistObject(
    @Json(name = "collaborative")
    val collaborative: Boolean? = null,
    @Json(name = "description")
    val description: String? = null,
    @Json(name = "external_urls")
    val externalUrls: Any? = null,
    @Json(name = "href")
    val href: String? = null,
    @Json(name = "id")
    val id: String? = null,
    @Json(name = "images")
    val images: List<ImageObject>? = null,
    @Json(name = "name")
    val name: String? = null,
    @Json(name = "owner")
    val owner: PublicUserObject? = null,
    @Json(name = "public")
    val public: Boolean? = null,
    @Json(name = "snapshot_id")
    val snapshotId: String? = null,
    @Json(name = "tracks")
    val tracks: PlaylistTracksInfo? = null,
    @Json(name = "type")
    val type: String? = null,
    @Json(name = "uri")
    val uri: String? = null
)

