/**
 * Spotify Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.clipfinder.spotify.api.models


import com.squareup.moshi.Json

/**
 *
 * @param uris A JSON array of the Spotify URIs to set, can be track or episode URIs. For example: {\"uris\": [\"spotify:track:4iV5W9uYEdYUVa79Axb7Rh\", \"spotify:track:1301WleyT98MSxVHPZCA6M\", \"spotify:episode:512ojhOuo1ktJprKbVcKyQ\"]} Currently, a maximum of 100 items can be set. Note: if the uris parameter is present in the query string, any URIs listed here in the body will be ignored.
 */

data class UrisBody(
    /* A JSON array of the Spotify URIs to set, can be track or episode URIs. For example: {\"uris\": [\"spotify:track:4iV5W9uYEdYUVa79Axb7Rh\", \"spotify:track:1301WleyT98MSxVHPZCA6M\", \"spotify:episode:512ojhOuo1ktJprKbVcKyQ\"]} Currently, a maximum of 100 items can be set. Note: if the uris parameter is present in the query string, any URIs listed here in the body will be ignored. */
    @Json(name = "uris")
    val uris: List<String>? = null
)

