/**
 * Spotify Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.clipfinder.spotify.api.model

import com.squareup.moshi.Json

/**
 *
 * @param timestamp
 * @param device
 * @param progressMs
 * @param isPlaying
 * @param currentlyPlayingType
 * @param item
 * @param shuffleState
 * @param repeatState
 * @param context
 */

data class CurrentPlaybackObject(
    @Json(name = "timestamp")
    val timestamp: java.time.OffsetDateTime,
    @Json(name = "device")
    val device: DeviceObject,
    @Json(name = "progress_ms")
    val progressMs: Int,
    @Json(name = "is_playing")
    val isPlaying: Boolean,
    @Json(name = "currently_playing_type")
    val currentlyPlayingType: String,
    @Json(name = "item")
    val item: TrackOrEpisodeObject,
    @Json(name = "shuffle_state")
    val shuffleState: Boolean,
    @Json(name = "repeat_state")
    val repeatState: String,
    @Json(name = "context")
    val context: ContextObject
)

