/**
 * Spotify Web API No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.clipfinder.spotify.api.model

import com.squareup.moshi.Json

/**
 *
 * @param id The device ID. This may be null.
 * @param isActive If this device is the currently active device.
 * @param isPrivateSession If this device is currently in a private session.
 * @param isRestricted Whether controlling this device is restricted. At present if this is “true”
 * then no Web API commands will be accepted by this device.
 * @param name The name of the device.
 * @param type Device type, such as “computer”, “smartphone” or “speaker”.
 * @param volumePercent The current volume in percent. This may be null.
 */
data class DeviceObject(
    /* The device ID. This may be null. */
    @Json(name = "id") val id: String,
    /* If this device is the currently active device. */
    @Json(name = "is_active") val isActive: Boolean,
    /* If this device is currently in a private session. */
    @Json(name = "is_private_session") val isPrivateSession: Boolean,
    /* Whether controlling this device is restricted. At present if this is “true” then no Web API commands will be accepted by this device. */
    @Json(name = "is_restricted") val isRestricted: Boolean,
    /* The name of the device. */
    @Json(name = "name") val name: String,
    /* Device type, such as “computer”, “smartphone” or “speaker”. */
    @Json(name = "type") val type: String,
    /* The current volume in percent. This may be null. */
    @Json(name = "volume_percent") val volumePercent: Int
)
