/**
 * Spotify Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.clipfinder.spotify.api.model


import com.squareup.moshi.Json

/**
 *
 * @param externalUrls
 * @param href A link to the Web API endpoint providing full details of the track.
 * @param id The Spotify ID for the track.
 * @param type The object type: \"track\".
 * @param uri The Spotify URI for the track.
 */

data class LinkedTrackObject(
    @Json(name = "external_urls")
    val externalUrls: Any,
    /* A link to the Web API endpoint providing full details of the track. */
    @Json(name = "href")
    val href: String,
    /* The Spotify ID for the track. */
    @Json(name = "id")
    val id: String,
    /* The object type: \"track\". */
    @Json(name = "type")
    val type: String,
    /* The Spotify URI for the track. */
    @Json(name = "uri")
    val uri: String
)

