/**
 * Spotify Web API No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.clipfinder.spotify.api.model

import com.squareup.moshi.Json
import org.threeten.bp.OffsetDateTime

/**
 *
 * @param context
 * @param playedAt The date and time the track was played.
 * @param track
 */
data class PlayHistoryObject(
    @Json(name = "context") val context: ContextObject,
    /* The date and time the track was played. */
    @Json(name = "played_at") val playedAt: OffsetDateTime,
    @Json(name = "track") val track: SimplifiedTrackObject
)
