/**
 * Spotify Web API No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.clipfinder.spotify.api.model

import com.clipfinder.core.spotify.model.ISpotifyPrivateUser
import com.squareup.moshi.Json

/**
 *
 * @param country The country of the user, as set in the user’s account profile. An ISO 3166-1
 * alpha-2 country code. This field is only available when the current user has granted access to
 * the user-read-private scope.
 * @param displayName The name displayed on the user’s profile. null if not available.
 * @param email The user’s email address, as entered by the user when creating their account.
 * Important! This email address is unverified; there is no proof that it actually belongs to the
 * user. This field is only available when the current user has granted access to the
 * user-read-email scope.
 * @param externalUrls
 * @param followers
 * @param href A link to the Web API endpoint for this user.
 * @param id The Spotify user ID for the user.
 * @param images The user’s profile image.
 * @param product The user’s Spotify subscription level: “premium”, “free”, etc. (The subscription
 * level “open” can be considered the same as “free”.) This field is only available when the current
 * user has granted access to the user-read-private scope.
 * @param type The object type: “user”
 * @param uri The Spotify URI for the user.
 */
data class PrivateUserObject(
    /* The country of the user, as set in the user’s account profile. An ISO 3166-1 alpha-2 country code. This field is only available when the current user has granted access to the user-read-private scope. */
    @Json(name = "country") val country: String,
    /* The name displayed on the user’s profile. null if not available. */
    @Json(name = "display_name") override val displayName: String? = null,
    /* The user’s email address, as entered by the user when creating their account. Important! This email address is unverified; there is no proof that it actually belongs to the user. This field is only available when the current user has granted access to the user-read-email scope. */
    @Json(name = "email") val email: String,
    @Json(name = "external_urls") val externalUrls: Any,
    @Json(name = "followers") val followers: FollowersObject? = null,
    /* A link to the Web API endpoint for this user. */
    @Json(name = "href") val href: String,
    /* The Spotify user ID for the user. */
    @Json(name = "id") override val id: String,
    /* The user’s profile image. */
    @Json(name = "images") override val images: List<ImageObject>? = null,
    /* The user’s Spotify subscription level: “premium”, “free”, etc. (The subscription level “open” can be considered the same as “free”.) This field is only available when the current user has granted access to the user-read-private scope. */
    @Json(name = "product") val product: String,
    /* The object type: “user” */
    @Json(name = "type") val type: String,
    /* The Spotify URI for the user. */
    @Json(name = "uri") val uri: String
) : ISpotifyPrivateUser
