/**
 * Spotify Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.clipfinder.spotify.api.model

import com.clipfinder.core.spotify.model.ISpotifySimplifiedPlaylist
import com.squareup.moshi.Json

/**
 *
 * @param collaborative
 * @param description
 * @param externalUrls
 * @param href
 * @param id
 * @param images
 * @param name
 * @param owner
 * @param public
 * @param snapshotId
 * @param tracks
 * @param type
 * @param uri
 */

data class SimplifiedPlaylistObject(
    @Json(name = "collaborative")
    val collaborative: Boolean,
    @Json(name = "description")
    override val description: String? = null,
    @Json(name = "external_urls")
    val externalUrls: Any,
    @Json(name = "href")
    override val href: String,
    @Json(name = "id")
    override val id: String,
    @Json(name = "images")
    override val images: List<ImageObject>,
    @Json(name = "name")
    override val name: String,
    @Json(name = "owner")
    val owner: PublicUserObject,
    @Json(name = "public")
    val public: Boolean? = null,
    @Json(name = "snapshot_id")
    val snapshotId: String,
    @Json(name = "tracks")
    val tracks: PlaylistTracksInfo,
    @Json(name = "type")
    val type: String,
    @Json(name = "uri")
    override val uri: String
) : ISpotifySimplifiedPlaylist
