/**
 * Spotify Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.clipfinder.spotify.api.model


import com.squareup.moshi.Json

/**
 *
 * @param start The starting point (in seconds) of the time interval.
 * @param duration The duration (in seconds) of the time interval.
 * @param confidence The confidence, from 0.0 to 1.0, of the reliability of the interval.
 */

data class TimeIntervalObject(
    /* The starting point (in seconds) of the time interval. */
    @Json(name = "start")
    val start: java.math.BigDecimal? = null,
    /* The duration (in seconds) of the time interval. */
    @Json(name = "duration")
    val duration: java.math.BigDecimal? = null,
    /* The confidence, from 0.0 to 1.0, of the reliability of the interval. */
    @Json(name = "confidence")
    val confidence: java.math.BigDecimal? = null
)

