/**
 * Spotify Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.clipfinder.spotify.api.model


import com.squareup.moshi.Json

/**
 *
 * @param deviceIds A JSON array containing the ID of the device on which playback should be started/transferred. For example:{device_ids:[\"74ASZWbe4lXaubB36ztrGX\"]} Note: Although an array is accepted, only a single device_id is currently supported. Supplying more than one will return 400 Bad Request
 * @param play true: ensure playback happens on new device. false or not provided: keep the current playback state.
 */

data class TransferPlaybackBody(
    /* A JSON array containing the ID of the device on which playback should be started/transferred. For example:{device_ids:[\"74ASZWbe4lXaubB36ztrGX\"]} Note: Although an array is accepted, only a single device_id is currently supported. Supplying more than one will return 400 Bad Request */
    @Json(name = "device_ids")
    val deviceIds: List<String>,
    /* true: ensure playback happens on new device. false or not provided: keep the current playback state. */
    @Json(name = "play")
    val play: Boolean? = null
)

