/**
 * Spotify Web API No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.clipfinder.spotify.api.model

import com.squareup.moshi.Json

/**
 *
 * @param uris A JSON array of the Spotify URIs to add. For example: {\"uris\":
 * [\"spotify:track:4iV5W9uYEdYUVa79Axb7Rh\",\"spotify:track:1301WleyT98MSxVHPZCA6M\",
 * \"spotify:episode:512ojhOuo1ktJprKbVcKyQ\"]} A maximum of 100 items can be added in one request.
 * Note: if the uris parameter is present in the query string, any URIs listed here in the body will
 * be ignored.
 * @param position The position to insert the items, a zero-based index. For example, to insert the
 * items in the first position: position=0 ; to insert the items in the third position: position=2.
 * If omitted, the items will be appended to the playlist. Items are added in the order they appear
 * in the uris array. For example: {\"uris\":
 * [\"spotify:track:4iV5W9uYEdYUVa79Axb7Rh\",\"spotify:track:1301WleyT98MSxVHPZCA6M\"],
 * \"position\": 3}
 */
data class UrisPositionBody(
    /* A JSON array of the Spotify URIs to add. For example: {\"uris\": [\"spotify:track:4iV5W9uYEdYUVa79Axb7Rh\",\"spotify:track:1301WleyT98MSxVHPZCA6M\", \"spotify:episode:512ojhOuo1ktJprKbVcKyQ\"]} A maximum of 100 items can be added in one request. Note: if the uris parameter is present in the query string, any URIs listed here in the body will be ignored. */
    @Json(name = "uris") val uris: List<String>? = null,
    /* The position to insert the items, a zero-based index. For example, to insert the items in the first position: position=0 ; to insert the items in the third position: position=2. If omitted, the items will be appended to the playlist. Items are added in the order they appear in the uris array. For example: {\"uris\": [\"spotify:track:4iV5W9uYEdYUVa79Axb7Rh\",\"spotify:track:1301WleyT98MSxVHPZCA6M\"], \"position\": 3} */
    @Json(name = "position") val position: Int? = null
)
